### ISSUE TITLE
different color/notification icons

### ISSUE THREAD

**Issue by fraggan** [xenserver/xenadmin#2192]
Hi, I would like to have different colors/notification icons down at the "notification tab" in XCP-ng Center. Now it's a red circle with a number in it. That kinda feels like an error message to me. It would be nice to see green ones when there are informal and maybe yellow with warnings and red when something is wrong.

Edit: Today I got the yellow icon when one of my hosts used to much memory. But the notification down at the "Notifications" showed a red one. Not a major thing but I would prefer same color there as in the "message view". Just to be able to see fast/easy if there is something I need to check now or if it can wait.

**Comment by kc284** [comment]
This number is the total number for all things requiring the user's attention and/or further action, not just alerts, but also failed events and updates. If all is ok, it's not deemed necessary to distract the user, hence successful events are not included in the count. The red colour was chosen in order to make it more visible. If you want to use different colours, you'll need to decide how the various types of notifications weigh against each other and it's still likely to convey the user the wrong impression.

**Comment by kc284** [comment]
If you got a red circle it means something has gone wrong; successful events do not cause the red circle to appear. Have you checked the Notifications > Events window to see what happened?
By the way, the behaviour I am describing is for the current repo, i.e. Citrix XenCenter; I can't account for any modifications XCP-ng Center may have made.

**Comment by fraggan** [comment]
![image](https://user-images.githubusercontent.com/3606827/44532550-a167d380-a6f3-11e8-8cad-26328bb68baf.png)

I got the red circle even with something that went ok, like the snapshot, below. I'm using xen-center in windows 7 from the latest xcp-ng release 7.5

![image](https://user-images.githubusercontent.com/3606827/44532585-b5133a00-a6f3-11e8-98b3-83ce0ca45971.png)

**Comment by kc284** [comment]
As mentioned above, alerts are always shown regardless of their severity and at the moment we're not planning to change this, hence I'm closing this issue.
