### ISSUE TITLE
Null Reference Exception when trying to import disk image (OVA)

### ISSUE THREAD

**Issue by borzel** [xenserver/xenadmin#2356]
**Problem:**
https://github.com/xcp-ng/xenadmin/issues/123

**Reason:**
the object `file` is null
https://github.com/xenserver/xenadmin/blob/970148e629c121ea70f35b4ce2e7c8d0ecf4a53d/XenAdmin/Wizards/ImportWizard/OVFStorageResource.cs#L115

**Possible Solution:**
https://github.com/xcp-ng/xenadmin/pull/125/files

**Comment by kc284** [comment]
The proposed change does fix the problem, however I think the issue here is rather that we attempted to get the file size at all. The code should have checked first the property CanCalculateDiskCapacity before calling RequiredDiskCapacity like elsewhere in the code. In fact, having two properties there that always have to be used in conjuction is not ideal, because it's easy to forget the check. I've submitted PR https://github.com/xenserver/xenadmin/pull/2357 which proposes their replacement with a single method.
