### ISSUE TITLE
View Consoles when XenCenter is connected by SSH tunnel

### ISSUE THREAD

**Issue by ander089** [xenserver/xenadmin#2403]
When I'm at work and I want to connect to my XenServer I'm using an SSH tunnel.
With XenCenter I can do everything instead of view console.
I find the the way changing the Console.location with the console.Connection.HostnameWithPort.
I will do a branch with this.

Another way can be implement Socks Proxy into XenCenter, but is more

**Comment by ander089** [comment]
I'm not able to push anything... How can I show you what I've done ?

**Comment by kc284** [comment]
Direct push to upstream repos is disabled for obvious reasons. Please fork the repo, push the changes into your fork, and then create a pull request to this one. Thanks.

**Comment by kc284** [comment]
There is a server side toolstack issue whereby the consoles are not refreshed when the IP changes, so the issue should be fixed there instead of providing a client side workaround. Currently the team is working on this. I'm closing this issue and PR #2404, will also add a reference to the fix once it is submitted.

**Comment by kc284** [comment]
Fix in https://github.com/xapi-project/xen-api/pull/4176.
